FROM node:20-alpine

WORKDIR /app
RUN mkdir -p /opt/node_modules
COPY ./package.json /app
COPY ./package-lock.json /app

RUN npm cache clean --force

RUN npm install --force

COPY ./ /app

RUN npm run build

ENV VITE_SOCKET='/socket.io'
ENV VITE_SERVER='/api'
ENV VITE_KHTNCHATBOT_SERVICE='http://127.0.0.1:5000'

# EXPOSE 3000

COPY . .

CMD ["npm", "run", "preview"]