FROM node:20-alpine

WORKDIR /app
RUN mkdir -p /opt/node_modules
COPY ./package.json /app
COPY ./package-lock.json /app

RUN npm cache clean --force

RUN npm install --force

COPY ./ /app

RUN npm run build

ENV VITE_SOCKET='/socket.io'
ENV VITE_SERVER='/api'
ENV VITE_KHTNCHATBOT_SERVICE='http://127.0.0.1:5000'
ENV VITE_CHATGPT_KEY='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'

COPY . .

CMD ["npm", "run", "preview"]