version: '3.8'
services:

  # Service cho MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"  # Expose MongoDB cổng
    volumes:
      - mongo-data:/data/db  # Dữ liệu MongoDB được lưu trong volume
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - luanvan-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=25072003
      - MONGO_INITDB_DATABASE=luan_van_2024
    command: mongod --auth
    restart: always  # Tùy chọn để container tự khởi động lại nếu dừng bất ngờ
  
  server:
    build:
      dockerfile: Dockerfile.prod
      context: ./server # đường dẫn đến folder server
    container_name: luanvan-server
    networks:
      - luanvan-network
      # - airflowv2_default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server/public/storage:/app/public/storage
    depends_on:
      - mongo  # Đảm bảo MongoDB đã sẵn sàng trước khi chạy Express
    stdin_open: true  # Để tương thích với '-it', cho phép tương tác
    tty: true         # Để tương thích với '-it', giữ terminal mở
    restart: always  # Tùy chọn để container tự khởi động lại nếu dừng bất ngờ

  client:
    build:
      dockerfile: Dockerfile.prod
      context: ./client # đường dẫn đến folder client
    container_name: luanvan-client
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - server  # Đảm bảo MongoDB đã sẵn sàng trước khi chạy Express
    stdin_open: true  # Tương thích với '-it', cho phép tương tác với container
    tty: true         # Tương thích với '-it', giữ terminal mở
    restart: always  # Tự động khởi động lại container nếu nó dừng bất ngờ
    networks:
      - luanvan-network
      # - airflowv2_default

  nginx:
    image: nginx:1.18.0
    ports:
      - "88:8000"  # Chạy nginx trên cổng 80
    restart: always  # Tùy chọn để container tự khởi động lại nếu dừng bất ngờ
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Cấu hình Nginx
      - ./client:/usr/share/nginx/html  # Mount mã nguồn client
    depends_on:
      - client
      - server
    networks:
      - luanvan-network
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  luanvan-network:
    driver: bridge
  # airflowv2_default:
  #   external: true
volumes:
  mongo-data:  # Volume cho MongoDB để lưu trữ dữ liệu
